### ISSUE TITLE
Fix Installer

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [GuestSneeze-OS/GuestSneezeOS-old#76]
Based on this issue https://github.com/zweiler2/HoloISO_Tweaked/issues/36#issuecomment-2243737716

**Comment by GuestSneezeOSDev** [comment]
Related https://github.com/zweiler2/HoloISO_Tweaked/issues/36#issuecomment-2243737716

**Comment by GuestSneezeOSDev** [comment]
I may add calamares but i need to test ir

**Comment by GuestSneezeOSDev** [comment]
Similar : https://github.com/LukeShortCloud/winesapOS/pull/853#issuecomment-2244160929

**Comment by GuestSneezeOSDev** [comment]
Remaking the installer will take a long time and i do not want GuestSneezeOS to be the `gentoo linux` of SteamOS

**Comment by GuestSneezeOSDev** [comment]
Calamares can be used in the GuestSneezeOS 7

**Comment by Labsdj** [comment]
The last iso cannot be install on Internal disk on my desktop

**Comment by Labsdj** [comment]
Make a guide how to install in disk i choose

**Comment by Labsdj** [comment]
![Captura de ecrã 2024-07-23 181637](https://github.com/user-attachments/assets/c0905fb5-d2bf-4263-ae16-4e3ca6c3c845)

**Comment by GuestSneezeOSDev** [comment]
I will see what i can do

**Comment by GuestSneezeOSDev** [comment]
https://github.com/GuestSneezeOS/GuestSneezeOS-winesap/issues/1 Related

**Comment by GuestSneezeOSDev** [comment]
@Labsdj type these command
```
sudo passwd root
su
cd newbackup
./install.sh
```

**Comment by GuestSneezeOSDev** [comment]
@nyxiereal would you like to help?

**Comment by GuestSneezeOSDev** [comment]
@Labsdj have you tried `pacman-key --init && pacman-key --populate archlinux`

**Comment by Labsdj** [comment]
Not try yet @GuestSneezeOSDev but the OS need to be easy to install for a initiate person like me or others

**Comment by Labsdj** [comment]
I think the command get a error https://aur.archlinux.org/packages/calamares-git this

**Comment by nyxiereal** [comment]
Nah vro im good

**Comment by GuestSneezeOSDev** [comment]
@Labsdj I think it was not that package ```https://aur.archlinux.org/calamares``` might be the package also to use it you should ***NOT*** be in `root`

**Comment by GuestSneezeOSDev** [comment]
Development will now be focused on https://github.com/GuestSneezeOS/GuestSneezeOS-winesap since i forgot to add some important code
